[package]
name = "advent_of_code_2016"
version = "0.1.0"
edition = "2021"
authors = ["Alain Jean PARES (ajp@p997.net"]

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive ="0.3.0"

[dev-dependencies]
cargo-aoc="0.3.7"

[[bin]]
name = "aoc"
path = "src/main.rs"